-- MySQL Database Schema
-- Generated by ERD Editor

CREATE TABLE `user` (
  `id` VARCHAR(255) NOT NULL,
  `pw` VARCHAR(255) NOT NULL,
  `nick` VARCHAR(255) NOT NULL,
  `create_date` TIMESTAMP DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_nick` (`nick`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='user';

CREATE TABLE `board` (
  `bno` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) COMMENT '외래키 참조: user.id',
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `create_date` TIMESTAMP DEFAULT now(),
  PRIMARY KEY (`bno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='board';

CREATE TABLE `reply` (
  `rno` INT NOT NULL AUTO_INCREMENT,
  `rauth` VARCHAR(255) COMMENT '외래키 참조: user.id',
  `bno` INT COMMENT '외래키 참조: board.bno',
  `rcon` VARCHAR(255) NOT NULL,
  `create_date` TIMESTAMP DEFAULT now(),
  PRIMARY KEY (`rno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='reply';

ALTER TABLE `board` ADD CONSTRAINT `fk_board_user_author`
  FOREIGN KEY (`author`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `reply` ADD CONSTRAINT `fk_reply_user_rauth`
  FOREIGN KEY (`rauth`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `reply` ADD CONSTRAINT `fk_reply_board_bno`
  FOREIGN KEY (`bno`) REFERENCES `board`(`bno`) ON DELETE NO ACTION ON UPDATE NO ACTION;

